Repository pingcap/kvproto, pull requests merged in 2019-10, with the labels that each got.

#465 import_sstpb: abstract rewrite rule into its own message
  pkg/import_sstpb/import_sstpb.pb.go
  proto/import_sstpb.proto
Labels: LGT2

#469 import_sstpb: return the downloaded SST range and whether it is empty
  pkg/import_sstpb/import_sstpb.pb.go
  proto/import_sstpb.proto
Labels: LGT1

#467 improve backup checksum feature
  pkg/backup/backup.pb.go
  pkg/import_sstpb/import_sstpb.pb.go
  pkg/metapb/metapb.pb.go
  proto/backup.proto
Labels: enhancement

#474 Cherry-pick several import_sstpb related PRs (#463, #465, #469) into v3.1
  pkg/import_sstpb/import_sstpb.pb.go
  proto/import_sstpb.proto
Labels: cherry pick

#475 import_sstpb,pdpb: update the Rust interface
  src/protobuf/import_sstpb.rs
  src/protobuf/import_sstpb_grpc.rs
  src/protobuf/pdpb.rs
Labels: cherry pick
