Repository pingcap/kvproto, pull requests merged in 2019-11, with the labels that each got.

#483 Allow CheckTxnStatusRequest specify rollback or not if txn not exist
  pkg/backup/backup.pb.go
  pkg/coprocessor/coprocessor.pb.go
  pkg/deadlock/deadlock.pb.go
  pkg/debugpb/debugpb.pb.go
  pkg/enginepb/enginepb.pb.go
  pkg/eraftpb/eraftpb.pb.go
  pkg/errorpb/errorpb.pb.go
  pkg/import_kvpb/import_kvpb.pb.go
  pkg/import_sstpb/import_sstpb.pb.go
  pkg/kvrpcpb/kvrpcpb.pb.go
  pkg/metapb/metapb.pb.go
  pkg/pdpb/pdpb.pb.go
  pkg/raft_cmdpb/raft_cmdpb.pb.go
  pkg/raft_serverpb/raft_serverpb.pb.go
  pkg/tikvpb/tikvpb.pb.go
  proto/kvrpcpb.proto
Labels: LGT1

#486 cherry-pick master #484 #472 to release 3.0
  pkg/coprocessor/coprocessor.pb.go
  pkg/deadlock/deadlock.pb.go
  pkg/debugpb/debugpb.pb.go
  pkg/enginepb/enginepb.pb.go
  pkg/eraftpb/eraftpb.pb.go
  pkg/errorpb/errorpb.pb.go
  pkg/import_kvpb/import_kvpb.pb.go
  pkg/import_sstpb/import_sstpb.pb.go
  pkg/kvrpcpb/kvrpcpb.pb.go
  pkg/metapb/metapb.pb.go
  pkg/pdpb/pdpb.pb.go
  pkg/raft_cmdpb/raft_cmdpb.pb.go
  pkg/raft_serverpb/raft_serverpb.pb.go
  pkg/tikvpb/tikvpb.pb.go
  proto/kvrpcpb.proto
Labels: cherry pick

#490 [3.1] import_sstpb: added a global SetDownloadSpeedLimit RPC (#485)
  pkg/import_sstpb/import_sstpb.pb.go
  proto/import_sstpb.proto
  src/protobuf/import_sstpb.rs
  src/protobuf/import_sstpb_grpc.rs
Labels: LGT1, cherry pick
