Repository pingcap/kvproto, pull requests merged in 2019-12, with the labels that each got.

#505 Fix broken Rust build by pinning the replace rev
  Cargo.toml
Labels: bug

#511 Cherry-pick the BR-related protobuf changes (#507, #509 and #510) to release-3.1
  pkg/backup/backup.pb.go
  pkg/import_sstpb/import_sstpb.pb.go
  proto/backup.proto
  proto/import_sstpb.proto
  src/protobuf/backup.rs
  src/protobuf/import_sstpb.rs
Labels: cherry pick

#521 cherry-pick #517 to release-3.1
  pkg/backup/backup.pb.go
  proto/backup.proto
  src/protobuf/backup.rs
Labels: LGT1

#532 pdpb: support specifying keys to split region
  pkg/pdpb/pdpb.pb.go
  proto/pdpb.proto
  src/protobuf/pdpb.rs
Labels: cherry pick
