Repository pingcap/kvproto, pull requests merged in 2020-05, with the labels that each got.

#616 Add sse_kms_key_id for S3 backup (#607)
  .gitignore
  pkg/backup/backup.pb.go
  pkg/import_sstpb/import_sstpb.pb.go
  proto/backup.proto
  src/protobuf/backup.rs
Labels: cherry pick

#617 [4.0] add task_id to kv context
  pkg/kvrpcpb/kvrpcpb.pb.go
  proto/kvrpcpb.proto
Labels: cherry pick

#620 pdpb: add down_peers and pending_peers in GetRegionResponse
  pkg/pdpb/pdpb.pb.go
  proto/pdpb.proto
Labels: LGT1

#621 pdpb: add down_peers and pending_peers in GetRegionResponse (#620)
  pkg/pdpb/pdpb.pb.go
  proto/pdpb.proto
Labels: LGT1, cherry pick
