Repository pingcap/kvproto, pull requests merged in 2020-04, with the labels that each got.

#597 *: update name and script
  pkg/pdpb/pdpb.pb.go
  pkg/replicate_mode/replicate_mode.pb.go
  pkg/replication_modepb/replication_modepb.pb.go
  proto/pdpb.proto
  proto/replicate_mode.proto
  proto/replication_modepb.proto
  scripts/generate_go.sh
Labels: enhancement

#598 import_sstpb: include file length and crc32 into the download response
  pkg/import_sstpb/import_sstpb.pb.go
  proto/import_sstpb.proto
Labels: LGT2

#607 Add sse_kms_key_id for S3 backup
  pkg/backup/backup.pb.go
  proto/backup.proto
Labels: LGT1

#608 Add sse_kms_key_id for S3 backup (#607)
  pkg/backup/backup.pb.go
  proto/backup.proto
Labels: cherry pick

#602 sst_importer: add write streaming request
  pkg/import_sstpb/import_sstpb.pb.go
  proto/import_sstpb.proto
Labels: LGT2, enhancement

#614 sst_importer: add write streaming request (#602)
  pkg/import_sstpb/import_sstpb.pb.go
  proto/import_sstpb.proto
Labels: cherry pick

#601 [3.1] import_sstpb: include file length and crc32 into the download response (#598)
  .circleci/config.yml
  pkg/import_sstpb/import_sstpb.pb.go
  proto/import_sstpb.proto
  src/protobuf/import_sstpb.rs
Labels: LGT1, cherry pick
