Repository pingcap/kvproto, pull requests merged in 2020-11, with the labels that each got.

#693 backup: add json table field for analyze
  pkg/backup/backup.pb.go
  proto/backup.proto
Labels: LGT2

#694 Add ReadIndexNotReady and ProposalInMergingMode error
  pkg/errorpb/errorpb.pb.go
  proto/errorpb.proto
Labels: LGT2

#698 Add ReadIndexNotReady and ProposalInMergingMode error (#694)
  pkg/errorpb/errorpb.pb.go
  proto/errorpb.proto
Labels: status/PTAL

#696 backup: add json table field for analyze (#693)
  pkg/backup/backup.pb.go
  proto/backup.proto
Labels: LGT1
