Repository pingcap/kvproto, pull requests merged in 2020-02, with the labels that each got.

#544 backup: add backup ddl to meta
  pkg/backup/backup.pb.go
  proto/backup.proto
Labels: LGT1

#543 *: refine scripts
  Makefile
  README.md
  generate_cpp.sh
  scripts/check.sh
  scripts/common.sh
  scripts/generate_cpp.sh
  scripts/generate_go.sh
Labels: LGT2

#564 txn: add forUpdateTs in lockInfo
  pkg/kvrpcpb/kvrpcpb.pb.go
  proto/kvrpcpb.proto
Labels: enhancement
