Repository pingcap/kvproto, pull requests merged in 2024-06, with the labels that each got.

#1245 raft_serverpb: add new ExtraMessage types for the snapshot gen precheck process
  proto/raft_serverpb.proto
  scripts/proto.lock
Labels: lgtm, approved, size/S

#1248 kvrpcpb: add key errors to split region response
  pkg/kvrpcpb/kvrpcpb.pb.go
  proto/kvrpcpb.proto
  scripts/proto.lock
Labels: approved, size/XXL, needs-1-more-lgtm

#1251 pdpb: support scan regions for range batch
  pkg/pdpb/pdpb.pb.go
  proto/pdpb.proto
  scripts/proto.lock
Labels: lgtm, approved, size/XXL
