Repository pingcap/kvproto, pull requests merged in 2024-09, with the labels that each got.

#1259 Support replacing lock by key for deadlock detector service
  pkg/deadlock/deadlock.pb.go
  pkg/kvrpcpb/kvrpcpb.pb.go
  proto/deadlock.proto
  proto/kvrpcpb.proto
  scripts/proto.lock
Labels: lgtm, approved, size/XXL

#1262 owner: modify resource manager owner to PD
  OWNERS_ALIASES
  proto/OWNERS
Labels: lgtm, approved, size/S

#1254 resource_manager: add a new runaway action SwitchGroup
  pkg/resource_manager/resource_manager.pb.go
  proto/resource_manager.proto
  scripts/proto.lock
Labels: lgtm, approved, size/XL

#1263 Add back nullalble = false for DeadlockRequest.entry
  pkg/deadlock/deadlock.pb.go
  proto/deadlock.proto
  scripts/proto.lock
Labels: lgtm, approved, size/L

#1261 runaway: Add processed_keys and request_ru to check
  pkg/resource_manager/resource_manager.pb.go
  proto/resource_manager.proto
  scripts/proto.lock
Labels: lgtm, approved, size/XL

#1255 br: add encryption config to streaming backup
  pkg/brpb/brpb.pb.go
  pkg/encryptionpb/encryptionpb.pb.go
  pkg/import_sstpb/import_sstpb.pb.go
  proto/brpb.proto
  proto/encryptionpb.proto
  proto/import_sstpb.proto
  scripts/check.sh
  scripts/proto.lock
Labels: lgtm, approved, size/XXL

#1264 resource_manager: add background resource limit
  pkg/resource_manager/resource_manager.pb.go
  proto/resource_manager.proto
  scripts/proto.lock
Labels: lgtm, approved, size/XL

#1267 cdc: add congested error
  pkg/cdcpb/cdcpb.pb.go
  proto/cdcpb.proto
  scripts/proto.lock
Labels: lgtm, approved, size/XL

#1269 br: add access key/secrets fields for aws kms
  pkg/encryptionpb/encryptionpb.pb.go
  proto/encryptionpb.proto
  scripts/proto.lock
Labels: lgtm, approved, size/XL

#1270 In-memory engine: add pre-load extra msg for pre-load when transfer leader
  pkg/raft_serverpb/raft_serverpb.pb.go
  proto/raft_serverpb.proto
  scripts/proto.lock
Labels: lgtm, approved, size/XL

#1272 added epoch history to log backup files
  pkg/brpb/brpb.pb.go
  proto/brpb.proto
  scripts/proto.lock
Labels: lgtm, approved, size/XXL

#1265 [DNM] Msg BroadcastTxnStatus; modify Heartbeat for resolved-ts improvement
  pkg/configpb/configpb.pb.gw.go
  pkg/kvrpcpb/kvrpcpb.pb.go
  pkg/tikvpb/tikvpb.pb.go
  proto/kvrpcpb.proto
  proto/tikvpb.proto
  scripts/proto.lock
Labels: lgtm, approved, size/XXL
