Repository pingcap/kvproto, pull requests merged in 2025-04, with the labels that each got.

#1300 Enhancement: Add more fields for compacted SST restore
  pkg/import_sstpb/import_sstpb.pb.go
  proto/import_sstpb.proto
  scripts/proto.lock
Labels: lgtm, approved, size/XL

#1304 [skip ci] Update OWNERS file
  OWNERS
  OWNERS_ALIASES
  proto/OWNERS
Labels: lgtm, approved, size/L, skip-issue-check

#1305 [skip ci] Update OWNERS file
  OWNERS
  OWNERS_ALIASES
  proto/OWNERS
Labels: lgtm, approved, size/L, skip-issue-check

#1306 [skip ci] Update OWNERS file
  OWNERS
  OWNERS_ALIASES
  proto/OWNERS
Labels: lgtm, approved, size/L, skip-issue-check

#1308 kvrpcpb: Add more fields in CommitRequest/Response to give more lock info
  pkg/kvrpcpb/kvrpcpb.pb.go
  proto/kvrpcpb.proto
  scripts/proto.lock
Labels: lgtm, approved, size/XXL

#1307 enhancement: add more fields for log backup compact and future restore
  .github/workflows/cpp-test.yaml
  .github/workflows/golang-test.yaml
  .github/workflows/rust-test.yaml
  build.rs
  pkg/brpb/brpb.pb.go
  pkg/import_sstpb/import_sstpb.pb.go
  proto/brpb.proto
  proto/import_sstpb.proto
  scripts/proto.lock
  src/lib.rs
Labels: lgtm, approved, size/XXL
