Repository pingcap/kvproto, pull requests merged in 2025-01, with the labels that each got.

#1287 added involved ts for compaction
  pkg/brpb/brpb.pb.go
  proto/brpb.proto
  scripts/proto.lock
Labels: lgtm, approved, size/XXL

#1281 Add ext full backup
  pkg/brpb/brpb.pb.go
  proto/brpb.proto
  scripts/proto.lock
Labels: lgtm, approved, size/XXL

#1283 restore: support skip some keys due before/after certain timestamp
  pkg/import_sstpb/import_sstpb.pb.go
  proto/import_sstpb.proto
  scripts/proto.lock
Labels: lgtm, approved, size/XL

#1292 br: pick changes of brpb to v8.5
  pkg/brpb/brpb.pb.go
  proto/brpb.proto
  scripts/proto.lock
Labels: lgtm, approved, size/XXL

#1291 pdpb: return NodeStore in StoreHeartbeatResponse.
  pkg/configpb/configpb.pb.gw.go
  pkg/pdpb/pdpb.pb.go
  proto/pdpb.proto
  scripts/proto.lock
Labels: lgtm, approved, size/XXL

#1293 configpb: revert changes to configpb as building with lower go version.
  pkg/configpb/configpb.pb.gw.go
Labels: lgtm, approved, size/S

#1273 pdpb: introduce QueryRegion stream
  pkg/pdpb/pdpb.pb.go
  proto/pdpb.proto
  scripts/proto.lock
Labels: lgtm, approved, size/XXL
